spring.application.name=projeto-de-estagio-api

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jackson.mapper.sort-properties-alphabetically=false
